### ISSUE TITLE
System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by RusliRusl** [EinfachEinAlex/VirtualAudioCable-LoopbackSetup#1]
Hi, this looks really promising!

I tried loading it up in Visual studio and running as an administrator but I'm getting the following error. Any idea?

System.Runtime.InteropServices.COMException
  HResult=0xE000020B
  Message=Exception from HRESULT: 0xE000020B
  Source=VirtualAudioCable-CS
  StackTrace:
   at VirtualAudioCable_CS.Audio.Interfaces.IPropertyStore.GetValue(PropertyKey& key, PropVariant& value)
   at VirtualAudioCable_CS.Audio.Property.PropertyStore.get_Item(PropertyKey key) in \VirtualAudioCable-CS\Audio\Property\PropertyStore.cs:line 30
   at VirtualAudioCable_CS.Audio.SetupManager.FindVirtualAudioCable() in \VirtualAudioCable-CS\Audio\SetupManager.cs:line 44
   at VirtualAudioCable_CS.Audio.SetupManager..ctor() in \VirtualAudioCable-CS\Audio\SetupManager.cs:line 23
   at VirtualAudioCable_CS.Program.Main(String[] args) in \VirtualAudioCable-CS\Program.cs:line 35

**Comment by AlexanderDotH** [comment]
Hey, thanks for the issue! I updated the guids for the Windows 21H1 update, it should work now. Take a look at the new release!

**Comment by RusliRusl** [comment]
Nice one, works like a charm!
